### ISSUE TITLE
OutOfMemory

### ISSUE THREAD

**Issue by pbelmann** [cerebis/neotax#3]
Hey,

I tried to initialize the database with

```
mvn exec:java -Dexec.mainClass=mzd.taxonomy.neo.NeoConsole -Dexec.args="--i nodes.dmp names.dmp"
```

but I always get OutOfMemory exception:

```
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building neotax 0.1.1
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- exec-maven-plugin:1.3.2:java (default-cli) @ neotax ---
[WARNING] Warning: killAfter is now deprecated. Do you need it ? Please comment on MEXEC-6.
Creating nodes...
[WARNING] 

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread     "GC-Monitor"
[WARNING] 
java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:293)
    at java.lang.Thread.run(Thread.java:744)
Caused by: java.lang.OutOfMemoryError: Java heap space
    at org.neo4j.kernel.impl.util.VersionedHashMap$EntrySet.iterator(VersionedHashMap.java:329)
    at org.neo4j.kernel.impl.util.VersionedHashMap$KeySet.iterator(VersionedHashMap.java:350)
    at java.util.Collections$SetFromMap.iterator(Collections.java:3904)
    at java.util.Collections$UnmodifiableCollection$1.<init>(Collections.java:1064)
    at java.util.Collections$UnmodifiableCollection.iterator(Collections.java:1063)
    at       org.neo4j.kernel.impl.api.StateHandlingStatementOperations.nodeGetLabels(StateHandlingStatementOperations.java:188)
    at org.neo4j.kernel.impl.api.ConstraintEnforcingEntityOperations.nodeSetProperty(ConstraintEnforcingEntityOperations.java:85)
    at org.neo4j.kernel.impl.api.LockingStatementOperations.nodeSetProperty(LockingStatementOperations.java:289)
    at org.neo4j.kernel.impl.api.OperationsFacade.nodeSetProperty(OperationsFacade.java:551)
    at org.neo4j.kernel.impl.core.NodeProxy.setProperty(NodeProxy.java:254)
    at mzd.taxonomy.neo.NeoDao.storeNodes(NeoDao.java:139)
    at mzd.taxonomy.neo.NeoDao.initialiseDatabase(NeoDao.java:425)
    at mzd.taxonomy.neo.NeoConsole.main(NeoConsole.java:259)
    ... 6 more
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
```

Are you using a MAVEN_OPTS configuration like

```
export MAVEN_OPTS="-Xms256m -XX:MaxPermSize=1024m -Xmx1024m"
```

?

**Comment by cerebis** [comment]
I'll put some in. I've overlooked that detail. Initializing a database requires a lot of memory.

**Comment by pbelmann** [comment]
Ok, so it works on a machine with 48 cores and 503.8G MEM.

**Comment by cerebis** [comment]
I lost my original half-written reply....

I realize I was being lazy with the database writes. I left it to be done in very large single transactions for each step. The issue is how best to split very large resulting updates into smaller transactions. To reduce the memory footprint, I have now implemented this but you could conceivably create an incomplete database if you just assume process completion means a complete database.

One side effect is that initialization is now slower. Paginating the relationship updates appears to have a noticeable impact on runtime, despite indexes.
